# Generated by Django 5.2 on 2026-09-29 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن همراه')),
                ('code', models.CharField(max_length=6, verbose_name='کد تأیید')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'درخواست کد یکبار مصرف',
                'verbose_name_plural': 'درخواست\u200cهای کد یکبار مصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن همراه')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام نمایشی')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='مسدود شده')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
