# Generated by Django 5.2 on 2026-10-04 09:28

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default=1, max_length=100, validators=[apps.accounts.models.validate_display_name], verbose_name='نام و نام خانوادگی / نام مستعار'),
            preserve_default=False,
        ),
    ]
