# Generated by Django 5.2 on 2026-09-29 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('source', models.CharField(choices=[('ADMIN', 'مدیر سیستم'), ('AUTO', 'سیستمی (داده\u200cمحور)'), ('SUGGESTED', 'پیشنهاد کاربران')], default='ADMIN', max_length=20, verbose_name='منبع تگ')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('PENDING', 'در انتظار تایید'), ('REJECTED', 'رد شده')], default='ACTIVE', max_length=20, verbose_name='وضعیت تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('strength', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='میزان قدرت/اطمینان (۰ تا ۱۰۰)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال و قابل نمایش')),
                ('source', models.CharField(choices=[('ADMIN', 'مدیر سیستم'), ('AUTO', 'سیستمی (داده\u200cمحور)'), ('SUGGESTED', 'پیشنهاد کاربران')], default='ADMIN', max_length=20, verbose_name='منبع انتساب')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_tags', to='places.place', verbose_name='مکان')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_places', to='tags.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'تگ مکان',
                'verbose_name_plural': 'تگ\u200cهای مکان\u200cها',
                'ordering': ['-strength', '-updated_at'],
                'unique_together': {('place', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='TagRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('threshold_percentage', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='حداقل درصد آرا برای فعال\u200cسازی')),
                ('minimum_votes', models.PositiveIntegerField(default=5, verbose_name='حداقل تعداد کل آرا برای اعمال قانون')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rules', to='questions.questionoption', verbose_name='گزینه مورد نظر')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rules', to='questions.question', verbose_name='سوال مرتبط')),
                ('target_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_rules', to='tags.tag', verbose_name='تگ هدف')),
            ],
            options={
                'verbose_name': 'قانون استنتاج تگ',
                'verbose_name_plural': 'قوانین استنتاج تگ\u200cها',
                'unique_together': {('question', 'option', 'target_tag')},
            },
        ),
    ]
