# Generated by Django 5.2 on 2026-09-29 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان بخش')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'بخش پرسشنامه',
                'verbose_name_plural': 'بخش\u200cهای پرسشنامه',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('text', models.CharField(max_length=300, verbose_name='متن سوال')),
                ('is_general', models.BooleanField(default=False, verbose_name='سوال عمومی (نمایش برای همه مکان\u200cها)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('categories', models.ManyToManyField(blank=True, related_name='questions', to='places.category', verbose_name='دسته\u200cبندی\u200cهای مرتبط (خالی یعنی عمومی برای همه)')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.section', verbose_name='بخش مرتبط')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان گزینه')),
                ('value', models.IntegerField(default=1, verbose_name='ارزش عددی/وزن گزینه (مثلاً برای محاسبات آماری)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه سوال',
                'verbose_name_plural': 'گزینه\u200cهای سوالات',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
