# Generated by Django 5.2 on 2026-09-29 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ (شناسه متنی)')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون یا کلاس CSS')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام مکان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس کامل')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='منطقه شهری')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس')),
                ('working_hours', models.CharField(blank=True, max_length=200, null=True, verbose_name='ساعات کاری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال و قابل نمایش')),
                ('categories', models.ManyToManyField(related_name='places', to='places.category', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('image', models.ImageField(upload_to='places/%Y/%m/', verbose_name='فایل تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر کاور')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'تصویر مکان',
                'verbose_name_plural': 'تصاویر مکان\u200cها',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
