# Generated by Django 5.2 on 2026-09-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('report_type', models.CharField(choices=[('PROBLEM', 'گزارش مشکل'), ('SUGGESTION', 'پیشنهاد اصلاح/بهبود')], default='PROBLEM', max_length=20, verbose_name='نوع گزارش')),
                ('reason', models.CharField(max_length=200, verbose_name='عنوان/دلیل گزارش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('RESOLVED', 'رسیدگی شده'), ('REJECTED', 'رد شده')], default='PENDING', max_length=20, verbose_name='وضعیت بررسی')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='places.place', verbose_name='مکان مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش کاربر',
                'verbose_name_plural': 'گزارش\u200cهای کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر متنی (اختیاری)')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], default='APPROVED', max_length=20, verbose_name='وضعیت بازخورد')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place', verbose_name='مکان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازخورد کاربر',
                'verbose_name_plural': 'بازخوردهای کاربران',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'place')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.questionoption', verbose_name='گزینه انتخابی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='سوال')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.review', verbose_name='بازخورد والد')),
            ],
            options={
                'verbose_name': 'پاسخ ساختاریافته',
                'verbose_name_plural': 'پاسخ\u200cهای ساختاریافته',
                'unique_together': {('review', 'question')},
            },
        ),
    ]
